config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    member do
      post 'start', action: 'start'
      post 'finish', action: 'finish'
      post 'failure', action: 'failure'
    end
    collection do
      get 'start', action: 'started_tasks'
      get 'finish', action: 'finished_tasks'
      get 'failure', action: 'failed_tasks'
    end
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

# devise_scope :user do
#   get 'login' => 'devise/sessions#new', as: :new_user_session
#   post 'login' => 'devise/sessions#create', as: :user_session
#   delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
#   get 'google_oauth2' => 'users/omniauth_callbacks#passthru'
#   post 'google_oauth2' => 'users/omniauth_callbacks#passthru'
#   get 'google_oauth2_callback' => 'users/omniauth_callbacks#google_oauth2'
#   post 'google_oauth2_callback' => 'users/omniauth_callbacks#google_oauth2'
# end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get '/ranking', to: 'home#ranking'
  get '/mypage', to: 'home#mypage'
  get '/settings', to: 'home#settings'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  with_options presence: true do
    validates :title
    validates :deadline
    validates :priority, numericality: { less_than_or_equal_to: 5, greater_than_or_equal_to: 1 }
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  # omniauthのコールバック時に呼ばれるメソッド
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index; end
    def ranking; end
    def mypage; end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  PENALTY = %w[親に電話する コーラ一気飲み 語尾に「にゃん」をつける 出会った人に一発芸をする 1日間1番上の写真をLINEのアイコンにする]
  
  def index 
    @tasks = Task.where(status: '未受注').all
  end
  
  def started_tasks
    @tasks = Task.where(status: '進行中').all
    render 'start'
  end
  
  def finished_tasks
    @tasks = Task.where(status: '達成').all
    render 'finish'
  end
  
  def failed_tasks
    @tasks = Task.where(status: '失敗').all
    render 'failure'
  end

  def new
    @task = Task.new
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    @task = current_user.tasks.build(task_params.merge(penalty: PENALTY.sample, status: '未受注'))
    if @task.save(task_params)
      redirect_to action: "index"
    else
      render "new"
    end
  end
  
  def start
    @task = Task.find(params[:id])
    @task.status = '進行中'
    @task.save
    redirect_to action: "started_tasks"
  end
  
  def finish
    @task = Task.find(params[:id])
    @task.status = '達成'
    @task.save
    redirect_to action:  "index"
  end
  
  def failure
    @task = Task.find(params[:id])
    @task.status = '失敗'
    @task.save
    redirect_to action: "failed_tasks"
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params.merge(penalty: PENALTY.sample))
      redirect_to action: "show"
    else
      render "edit"
    end
  end

  private
    def task_params
      params.require(:task).permit(:title, :deadline, :priority, :detail)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    callback_for(:google)
  end

  # common callback method
  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<div class="flex justify-center items-center h-full">
  <div class="flex flex-col">
  <h1 class="text-4xl mb-8 text-center">タスクエスト!!</h1>
  <div>
  <button class="px-4 py-2 font-medium tracking-wide text-white capitalize transition-colors duration-200 transform bg-blue-600 rounded-md hover:bg-blue-500 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-80">
    <%= link_to "Googleでログイン", user_google_oauth2_omniauth_authorize_path, method: :post, class: 'btn btn-default btn-primary' %>
  </button>
  <button class="px-4 py-2 font-medium tracking-wide text-white capitalize transition-colors duration-200 transform bg-gray-600 rounded-md hover:bg-gray-500 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-80">
    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
  </button>
  </div>
  </div>
</div>

app/views/home/mypage.html.erb
<div class="flex justify-center m-4 text-2xl">
    <h2>マイページ</h2>
</div>

app/views/home/ranking.html.erb
<div class="flex justify-center m-4 text-2xl">
    <h2>冒険者ランキング</h2>
</div>

app/views/home/settings.html.erb
<div class="flex justify-center m-4 text-2xl">
    <h2>冒険準備</h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <div class="flex relative">
      <% if user_signed_in? %>
      <div id="menu" class="hidden fixed left-0 lg:static lg:flex flex-col w-96 h-screen py-8 bg-white border-r dark:bg-gray-800 dark:border-gray-600">
        <h2 class="text-3xl font-semibold text-center text-gray-800 dark:text-white">Menu</h2>
        <div class="flex flex-col items-center mt-6 -mx-2">
            <img class="object-cover w-24 h-24 mx-2 rounded-full" src="https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80" alt="avatar">
            <h4 class="mx-2 mt-2 font-medium text-gray-800 dark:text-gray-200 hover:underline">勇者ヨシヒコ</h4>
            <p class="mx-2 mt-1 text-sm font-medium text-gray-600 dark:text-gray-400 hover:underline"><%= current_user.email %></p>
        </div>
        
        <div class="flex flex-col justify-between flex-1 mt-6">
            <nav>
                <a class="flex items-center px-4 py-2 text-gray-600 transition-colors duration-200 transform dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700 dark:hover:text-gray-200 hover:text-gray-700" href="/">
                    <i class="fas fa-gopuram text-xl"></i>
                    <span class="mx-4 font-medium">ログイン</span>
                </a>
                
                <a class="flex items-center px-4 py-2 mt-5 text-gray-600 transition-colors duration-200 transform dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700 dark:hover:text-gray-200 hover:text-gray-700" href="/tasks/new">
                    <i class="fas fa-scroll"></i>
                    <span class="mx-4 font-medium">クエストを立てる</span>
                </a>

                <a class="flex items-center px-4 py-2 mt-5 text-gray-600 transition-colors duration-200 transform dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700 dark:hover:text-gray-200 hover:text-gray-700" href="/tasks">
                    <i class="fas fa-dungeon"></i>
                    <span class="mx-4 font-medium">クエストボード</span>
                </a>

                <a class="flex items-center px-4 py-2 mt-5 text-gray-600 transition-colors duration-200 transform dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700 dark:hover:text-gray-200 hover:text-gray-700" href="/tasks/start">
                    <i class="fas fa-scroll"></i>
                    <span class="mx-4 font-medium">進行中のクエスト</span>
                </a>

                <a class="flex items-center px-4 py-2 mt-5 text-gray-600 transition-colors duration-200 transform dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700 dark:hover:text-gray-200 hover:text-gray-700" href="/tasks/failure">
                    <i class="fas fa-scroll"></i>
                    <span class="mx-4 font-medium">失敗したクエスト</span>
                </a>

                <a class="flex items-center px-4 py-2 mt-5 text-gray-600 transition-colors duration-200 transform dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700 dark:hover:text-gray-200 hover:text-gray-700" href="/tasks/finish">
                    <i class="fas fa-scroll"></i>
                    <span class="mx-4 font-medium">達成済みのクエスト</span>
                </a>
                
                <a class="flex items-center px-4 py-2 mt-5 text-gray-600 transition-colors duration-200 transform dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700 dark:hover:text-gray-200 hover:text-gray-700" href="/ranking">
                    <i class="fas fa-crown"></i>
                    <span class="mx-4 font-medium">冒険者ランキングを見る</span>
                </a>

                <a class="flex items-center px-4 py-2 mt-5 text-gray-600 transition-colors duration-200 transform dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700 dark:hover:text-gray-200 hover:text-gray-700" href="/mypage">
                    <i class="fas fa-id-card"></i>
                    <span class="mx-4 font-medium">ギルドカード</span>
                </a>

                <a class="flex items-center px-4 py-2 mt-5 text-gray-600 transition-colors duration-200 transform dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700 dark:hover:text-gray-200 hover:text-gray-700" href="/settings">
                    <i class="fas fa-cog text-xl"></i>
                    <span class="mx-4 font-medium">冒険準備</span>
                </a>
            </nav>
        </div>
    </div>
      <button id="menuBtn" class="lg:hidden fixed left-4 top-4">
          <i id="menuBtnOpen" class="fas fa-bars fa-2x"></i>
          <i id="menuBtnClose" class="fas fa-times fa-2x hidden"></i>
      </button>
      <% end %>
      <!-- contents -->
      <!--<p class="notice"><%= notice %></p>-->
      <!--<p class="alert"><%= alert %></p>-->
      <div class="w-full h-screen">
        <%= yield %>
      </div>
    </div>
    

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="flex justify-center m-4 text-2xl">
    <h2>クエストの編集</h2>
</div>

<%= form_for @task do |form| %>
<section class="text-gray-600 body-font relative">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-12">
        <%= form.label :title, "クエストのタイトル", class: 'leading-7 text-gray-600 text-4xl mb-8' %>
        <%= form.text_field :title, class: 'sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900 text-center w-3/5 m-auto bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out' %>
        <% if @task.errors.include?(:title) %>
           <p class="text-red-400"><%= @task.errors.full_messages_for(:title).first %></p>
        <% end %>
      
        <%= form.label :detail, "クエストの詳細", class: 'leading-7 text-gray-600 text-2xl mb-4' %>
        <%= form.text_area :detail, class: ' mx-auto leading-relaxed text-base w-3/5 h-fit bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out' %>
        <% if @task.errors.include?(:detail) %>
           <p class="text-red-400"><%= @task.errors.full_messages_for(:detail).first %></p>
        <% end %>
        
    </div>
    <div class="lg:w-1/2 md:w-2/3 mx-auto">
      <div class="flex flex-wrap -m-2">
        <div class="p-2 w-1/2">
          <div class="relative">
            <label for="name" class="leading-7 text-sm text-gray-600">優先度</label>
            <%= form.number_field :priority, class: 'text-sm mb-4 text-gray-900 text-center w-3/5 m-auto bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 outline-none text-gray-700 py-0.5 px-1 leading-8 transition-colors duration-200 ease-in-out' %>
            <% if @task.errors.include?(:priority) %>
               <p class="text-red-400"><%= @task.errors.full_messages_for(:priority).first %></p>
            <% end %>
          </div>
        </div>
        <div class="p-2 w-1/2">
          <div class="relative">
            <label for="email" class="leading-7 text-sm text-gray-600">〆切</label>
            <%= form.date_field :deadline, class: 'text-sm mb-4 text-gray-900 text-center w-3/5 m-auto bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 outline-none text-gray-700 py-0.5 px-1 leading-8 transition-colors duration-200 ease-in-out' %>
            <% if @task.errors.include?(:deadline) %>
               <p class="text-red-400"><%= @task.errors.full_messages_for(:deadline).first %></p>
            <% end %>
          </div>
        </div>
        
        <div class="p-2 m-auto">
          <button class="flex justify-center mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg"><%= form.submit %></button>
        </div>
      </div>
    </div>
  </div>
</section>
<% end %>

app/views/tasks/failure.html.erb
<div class="flex justify-center m-4 text-2xl">
    <h1>失敗したクエスト</h1>
</div>

<div class="focus:outline-none py-8 lg:w-full w-11/12 m-auto">
    <div class="lg:flex-wrap lg:flex items-center justify-center w-full gap-y-8">
        
        <% if @tasks.blank? %>
        <h1>失敗したクエストはありません！！</h1>
        <% end %>
        <% @tasks.each do |task| %>
            <%= link_to task_path(task), class: "focus:outline-none lg:w-4/12 lg:mr-7 lg:mb-0 mb-7 bg-white p-6 shadow rounded block hover:shadow-xl duration-200" do %>
                <div class="flex items-center border-b border-gray-200 pb-6">
                    <div class="flex items-start justify-between w-full">
                        <div class="pl-3 w-full">
                            <p tabindex="0" class="focus:outline-none text-xl font-medium leading-5 text-gray-800"><%= task.title %></p>
                            <p tabindex="0" class="focus:outline-none text-sm leading-normal pt-2 text-gray-500">締切日：<%= task.deadline %></p>
                        </div>
                    </div>
                </div>
                <div class="px-2">
                    <div tabindex="0" class="focus:outline-none flex pt-4">
                        <% 5.times do |index| %>
                            <% if task.priority > index %>
                                <i class="fas fa-star"></i>
                            <% else %>
                                <i class="far fa-star"></i>
                            <% end %>  
                        <% end %>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/tasks/finish.html.erb
<div class="flex justify-center m-4 text-2xl">
    <h1>達成済みのクエスト</h1>
</div>

<div class="focus:outline-none py-8 lg:w-full w-11/12 m-auto">
    <div class="lg:flex-wrap lg:flex items-center justify-center w-full gap-y-8">
        
        <% if @tasks.blank? %>
        <h1>達成済みのクエストはありません！！</h1>
        <% end %>
        <% @tasks.each do |task| %>
            <%= link_to task_path(task), class: "focus:outline-none lg:w-4/12 lg:mr-7 lg:mb-0 mb-7 bg-white p-6 shadow rounded block hover:shadow-xl duration-200" do %>
                <div class="flex items-center border-b border-gray-200 pb-6">
                    <div class="flex items-start justify-between w-full">
                        <div class="pl-3 w-full">
                            <p tabindex="0" class="focus:outline-none text-xl font-medium leading-5 text-gray-800"><%= task.title %></p>
                            <p tabindex="0" class="focus:outline-none text-sm leading-normal pt-2 text-gray-500">締切日：<%= task.deadline %></p>
                        </div>
                    </div>
                </div>
                <div class="px-2">
                    <div tabindex="0" class="focus:outline-none flex pt-4">
                        <% 5.times do |index| %>
                            <% if task.priority > index %>
                                <i class="fas fa-star"></i>
                            <% else %>
                                <i class="far fa-star"></i>
                            <% end %>  
                        <% end %>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/tasks/index.html.erb
<div class="flex justify-center m-4 text-2xl">
    <h2>未受注のクエスト</h2>
</div>

<div class="focus:outline-none py-8 lg:w-full w-11/12 m-auto">
    <div class="lg:flex-wrap lg:flex items-center justify-center w-full gap-y-8">
        
        <% if @tasks.blank? %>
        <h1>タスクが一つも立てられていません！！</h1>
        <% end %>
        <% @tasks.each do |task| %>
            <%= link_to task_path(task), class: "focus:outline-none lg:w-4/12 lg:mr-7 lg:mb-0 mb-7 bg-white p-6 shadow rounded block hover:shadow-xl duration-200" do %>
                <div class="flex items-center border-b border-gray-200 pb-6">
                    <div class="flex items-start justify-between w-full">
                        <div class="pl-3 w-full">
                            <p tabindex="0" class="focus:outline-none text-xl font-medium leading-5 text-gray-800"><%= task.title %></p>
                            <p tabindex="0" class="focus:outline-none text-sm leading-normal pt-2 text-gray-500">締切日：<%= task.deadline %></p>
                        </div>
                    </div>
                </div>
                <div class="px-2">
                    <div tabindex="0" class="focus:outline-none flex pt-4">
                        <% 5.times do |index| %>
                            <% if task.priority > index %>
                                <i class="fas fa-star"></i>
                            <% else %>
                                <i class="far fa-star"></i>
                            <% end %>  
                        <% end %>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/tasks/new.html.erb
<div class="flex justify-center m-4 text-2xl">
    <h2>クエストを立てる</h2>
</div>

<%= form_for @task do |form| %>
<section class="text-gray-600 body-font relative">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-12">
        <%= form.label :title, "クエストのタイトル", class: 'leading-7 text-gray-600 text-4xl mb-8' %>
        <%= form.text_field :title, class: 'sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900 text-center w-3/5 m-auto bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out' %>
        <% if @task.errors.include?(:title) %>
           <p class="text-red-400"><%= @task.errors.full_messages_for(:title).first %></p>
        <% end %>
      
        <%= form.label :detail, "クエストの詳細", class: 'leading-7 text-gray-600 text-2xl mb-4' %>
        <%= form.text_area :detail, class: ' mx-auto leading-relaxed text-base w-3/5 h-fit bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out' %>
        <% if @task.errors.include?(:detail) %>
           <p class="text-red-400"><%= @task.errors.full_messages_for(:detail).first %></p>
        <% end %>
        
    </div>
    <div class="lg:w-1/2 md:w-2/3 mx-auto">
      <div class="flex justify-around -m-2">
        <div class="p-2 w-6/12">
          <div class="relative">
            <label for="name" class="leading-7 text-sm text-gray-600">優先度</label>
            <%= form.number_field :priority, class: 'text-sm mb-4 text-gray-900 text-center w-3/5 m-auto bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 outline-none text-gray-700 py-0.5 px-1 leading-8 transition-colors duration-200 ease-in-out' %>
            <% if @task.errors.include?(:priority) %>
               <p class="text-red-400"><%= @task.errors.full_messages_for(:priority).first %></p>
            <% end %>
          </div>
        </div>
        <div class="p-2 w-6/12">
          <div class="relative">
            <label for="email" class="leading-7 text-sm text-gray-600">〆切</label>
            <%= form.date_field :deadline, class: 'text-sm mb-4 text-gray-900 text-center w-3/5 m-auto bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 outline-none text-gray-700 py-0.5 px-1 leading-8 transition-colors duration-200 ease-in-out w-fit' %>
            <% if @task.errors.include?(:deadline) %>
               <p class="text-red-400"><%= @task.errors.full_messages_for(:deadline).first %></p>
            <% end %>
          </div>
        </div>
        
      </div>
        <div class="p-2 m-auto">
          <button class="flex justify-center mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg"><%= form.submit %></button>
        </div>
    </div>
  </div>
</section>
<% end %>

app/views/tasks/show.html.erb
<div class="flex justify-center m-4 text-2xl">
    <h2>クエストの詳細</h2>
</div>

<section class="text-gray-600 body-font relative">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-12">
        <h1 class="leading-7 text-gray-600 text-4xl mb-8"><%= @task.title %></h1>
        <p class="leading-7 text-gray-600 text-2xl mb-4"><%= @task.detail %></p>
    </div>
    <div class="lg:w-1/2 md:w-2/3 mx-auto">
      <div class="flex flex-wrap -m-2">
        <div class="p-2 w-1/2">
          <div class="relative">
            <label for="name" class="leading-7 text-sm text-gray-600">優先度</label>
            <div tabindex="0" class="focus:outline-none flex pt-4">
                <% 5.times do |index| %>
                    <% if @task.priority > index %>
                        <i class="fas fa-star"></i>
                    <% else %>
                        <i class="far fa-star"></i>
                    <% end %>  
                <% end %>
            </div>
          </div>
        </div>
        <div class="p-2 w-1/2">
          <div class="relative">
            <label for="email" class="leading-7 text-sm text-gray-600">〆切</label>
            <p><%= @task.deadline %></p>
          </div>
        </div>
        
        <div class="p-2 w-1/2 mb-4">
          <div class="relative">
            <label for="message" class="leading-7 text-sm text-gray-600">ペナルティ</label>
            <p><%= @task.penalty %></p>
          </div>
        </div>

        
      </div>
      <div class="p-2 m-auto flex flex-wrap justify-around gap-y-4">
          <button class="w-5/12 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg"><%= link_to '受注する', start_task_path(@task), method: 'post' %></button>
          <button class="w-5/12 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg"><%= link_to '完了する', finish_task_path(@task), method: 'post' %></button>
          <button class="w-5/12 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg"><%= link_to '諦める', failure_task_path(@task), method: 'post' %></button>
          <button class="w-5/12 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg"><%= link_to '編集する', edit_task_path(@task), method: 'get' %></button>
      </div>
    </div>
  </div>
</section>

app/views/tasks/start.html.erb
<div class="flex justify-center m-4 text-2xl">
    <h1>進行中のクエスト</h1>
</div>

<div class="focus:outline-none py-8 lg:w-full w-11/12 m-auto">
    <div class="lg:flex-wrap lg:flex items-center justify-center w-full gap-y-8">
        
        <% if @tasks.blank? %>
        <h1>進行中のクエストはありません！！</h1>
        <% end %>
        <% @tasks.each do |task| %>
            <%= link_to task_path(task), class: "focus:outline-none lg:w-4/12 lg:mr-7 lg:mb-0 mb-7 bg-white p-6 shadow rounded block hover:shadow-xl duration-200" do %>
                <div class="flex items-center border-b border-gray-200 pb-6">
                    <div class="flex items-start justify-between w-full">
                        <div class="pl-3 w-full">
                            <p tabindex="0" class="focus:outline-none text-xl font-medium leading-5 text-gray-800"><%= task.title %></p>
                            <p tabindex="0" class="focus:outline-none text-sm leading-normal pt-2 text-gray-500">締切日：<%= task.deadline %></p>
                        </div>
                    </div>
                </div>
                <div class="px-2">
                    <div tabindex="0" class="focus:outline-none flex pt-4">
                        <% 5.times do |index| %>
                            <% if task.priority > index %>
                                <i class="fas fa-star"></i>
                            <% else %>
                                <i class="far fa-star"></i>
                            <% end %>  
                        <% end %>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>


<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>